apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: kubevirt-vm-operator
rules:
- apiGroups:
  - "kubevirt.io"
  resources:
  - virtualmachines
  - virtualmachineinstances
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - kubevirt-vm-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - guest.kubevirt.io
  resources:
  - '*'
  verbs:
  - '*'
