// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/masayag/kubevirt-vm-operator/pkg/apis/guest/v1alpha1.Fedora":       schema_pkg_apis_guest_v1alpha1_Fedora(ref),
		"github.com/masayag/kubevirt-vm-operator/pkg/apis/guest/v1alpha1.FedoraSpec":   schema_pkg_apis_guest_v1alpha1_FedoraSpec(ref),
		"github.com/masayag/kubevirt-vm-operator/pkg/apis/guest/v1alpha1.FedoraStatus": schema_pkg_apis_guest_v1alpha1_FedoraStatus(ref),
	}
}

func schema_pkg_apis_guest_v1alpha1_Fedora(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Fedora is the Schema for the fedoras API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/masayag/kubevirt-vm-operator/pkg/apis/guest/v1alpha1.FedoraSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/masayag/kubevirt-vm-operator/pkg/apis/guest/v1alpha1.FedoraStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/masayag/kubevirt-vm-operator/pkg/apis/guest/v1alpha1.FedoraSpec", "github.com/masayag/kubevirt-vm-operator/pkg/apis/guest/v1alpha1.FedoraStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_guest_v1alpha1_FedoraSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FedoraSpec defines the desired state of Fedora",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_guest_v1alpha1_FedoraStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "FedoraStatus defines the observed state of Fedora",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
